### ISSUE TITLE
docs: pub activate issue and restricted docs

### ISSUE THREAD

**Issue by HayesGordon** [wolfenrain/umbra#9]
Awesome package and can't wait to play around with it.

The doc mentioned in the readme is giving a 404: https://github.com/wolfenrain/umbra/tree/main/docs

And running `dart pub global activate umbra_cli`

Gives:
```
dart pub global activate umbra_cli
Because pub global activate depends on umbra_cli any which doesn't exist
  (could not find package umbra_cli at https://pub.dartlang.org), version
  solving failed
```

**Comment by wolfenrain** [comment]
Hi both of those are correct, as I havent yet published the CLI nor written the documentation!

Planning on doing the docs in my next PR, had to make the API less opinionated.

If you want to play around with it already you can clone it locally and run `dart pub global activate --source path .` inside `packages/umbra_cli` to get the CLI installed.

**Comment by HayesGordon** [comment]
Already did that and played around! This is a really nice initiative, thanks for the work.

**Comment by wolfenrain** [comment]
I just released the first dev version! So closing this issue ;-).
